In [3]:
import numpy as np

output = np.zeros((7,7))

output

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [4]:
z = np.ones((5, 5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
z[2, 2] = 5

output[1:-1, 1:-1] = z
output

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [21]:
import numpy as np

a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 11]))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 11]])

In [22]:
b = np.max(a, axis=1).sum()

In [23]:
b

16

In [25]:
a = np.ones((2, 4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
b = a.reshape((4, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
